<a href="https://colab.research.google.com/github/Vigneshgvs/DataScience6150/blob/main/VigneshAsgmt6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Machine (SVM) - Linear

## Importing the libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [6]:
dataset = pd.read_excel('loan.xlsx', header=0)


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
dataset = pd.get_dummies(dataset)
dataset.head()

Age  Time_at_address  ...  Decision_accept  Decision_reject
0  50.750000            0.585  ...                0                1
1  19.670000           10.000  ...                0                1
2  52.830002           15.000  ...                1                0
3  22.670000            2.540  ...                1                0
4  29.250000           13.000  ...                0                1

[5 rows x 37 columns]

In [8]:
del dataset['Decision_reject']
del dataset['Acc_ref_oth_inst_']
del dataset['Liab_ref_t']
del dataset['Job_status_unemploye']
del dataset['Occupation_unemploye']
del dataset['Telephone_not_given']
del dataset['Res_status_rent']
del dataset['Sex_M']
dataset.head()

Age  Time_at_address  ...  Acc_ref_given  Decision_accept
0  50.750000            0.585  ...              1                0
1  19.670000           10.000  ...              1                0
2  52.830002           15.000  ...              1                1
3  22.670000            2.540  ...              1                1
4  29.250000           13.000  ...              1                0

[5 rows x 29 columns]

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[50.75        0.58499998  0.         ...  0.          1.
   1.        ]
 [19.67000008 10.          0.         ...  0.          0.
   1.        ]
 [52.83000183 15.          5.         ...  0.          1.
   1.        ]
 ...
 [23.32999992  1.5         1.         ...  0.          1.
   1.        ]
 [21.          4.78999996  2.         ...  0.          0.
   1.        ]
 [27.75        1.28999996  0.         ...  0.          0.
   0.        ]]
[0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1 1 1 0 0 0
 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 0 1
 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0
 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 1
 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0
 0 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0
 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 

## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
print("X_train ------------")
print(X_train)
print("y_train ------------")
print(y_train)
print("X_test ------------")
print(X_test)
print("y_test ------------")
print(y_test)

X_train ------------
[[23.42000008  0.79000002  1.         ...  0.          0.
   1.        ]
 [44.25        0.5        10.         ...  0.          1.
   0.        ]
 [26.07999992  8.66499996  1.         ...  0.          1.
   1.        ]
 ...
 [20.5         2.41499996  2.         ...  0.          0.
   1.        ]
 [25.25       12.5         1.         ...  0.          0.
   1.        ]
 [20.25        9.96000004  0.         ...  1.          1.
   1.        ]]
y_train ------------
[1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0
 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0
 1 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0
 0 1 1 0 1 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0
 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1
 1 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 1

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print("X_train------")
print(X_train)
print("X_test-------")
print(X_test)

X_train------
[[-0.67478237 -0.81137061 -0.27116101 ... -0.12162606 -1.06321907
   0.27429019]
 [ 1.12187368 -0.87173218  2.44661186 ... -0.12162606  0.94053994
  -3.64577381]
 [-0.44534862  0.8277581  -0.27116101 ... -0.12162606  0.94053994
   0.27429019]
 ...
 [-0.92664198 -0.47313771  0.03081375 ... -0.12162606 -1.06321907
   0.27429019]
 [-0.51693885  1.62598779 -0.27116101 ... -0.12162606 -1.06321907
   0.27429019]
 [-0.9482053   1.09730373 -0.57313578 ...  8.22192192  0.94053994
   0.27429019]]
X_test-------
[[-0.91197891  0.12527436 -0.57313578 ... -0.12162606  0.94053994
   0.27429019]
 [ 0.97093042  0.04722061  0.33278852 ... -0.12162606 -1.06321907
   0.27429019]
 [ 0.89157755 -0.61155302 -0.57313578 ... -0.12162606  0.94053994
   0.27429019]
 ...
 [-0.17192569  1.73005945 -0.57313578 ... -0.12162606  0.94053994
   0.27429019]
 [ 2.76758662 -0.86340645 -0.57313578 ... -0.12162606 -1.06321907
   0.27429019]
 [-0.64631879 -0.88942437 -0.57313578 ... -0.12162606  0.94053994
   0

## Training the SVM model on the Training set

In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)  #default C=1.0
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Predicting a new result

sample_test_row = df.loc[[1]]
print(sample_test_row)

In [15]:
sample_test_row = X_test[1]
print(sample_test_row)

[ 0.97093042  0.04722061  0.33278852 -0.58514498 -0.83472932  0.10704839
 -0.69631062 -1.90660304 -1.90660304 -0.52449303 -0.19847907 -0.2283577
 -0.28638947 -0.32626923 -0.27429019 -0.35297332  2.92023591 -0.22120051
 -0.27429019 -0.2283577  -0.46972393 -0.05407381  0.79582243 -0.14433757
 -0.32077078 -0.12162606 -1.06321907  0.27429019]


In [16]:
print(classifier.predict(sc.transform([sample_test_row])))

[0]


## Predicting the Test set results

In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]]


## Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[46  4]
 [13 23]]


0.8023255813953488

In [19]:
classifier.n_support_

array([87, 87], dtype=int32)

## Grid Search

In [20]:
from sklearn.model_selection import GridSearchCV 
params = {'C':(0.001,0.005,0.01,0.05, 0.1, 0.5, 1, 5, 10, 50,100,500,1000)} 
clf_svm_l = SVC(kernel='linear')
svm_grid_lin = GridSearchCV(clf_svm_l, params, n_jobs=-1,
                            cv=10, verbose=1, scoring='accuracy') 
svm_grid_lin.fit(X_train, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [21]:
svm_grid_lin.best_params_ 

{'C': 0.5}

In [22]:
linsvm_clf = svm_grid_lin.best_estimator_
accuracy_score(y_test, linsvm_clf.predict(X_test))

0.7906976744186046

# Support Vector Machine (SVM) - Poly

In [23]:
classifier_poly = SVC(kernel='poly', degree=2, C=0.1)
classifier_poly.fit(X_train, y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [24]:
y_train_pred = classifier_poly.predict(X_train)
y_test_pred = classifier_poly.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.5930232558139535

In [25]:
classifier_poly.n_support_

array([166, 155], dtype=int32)

# Support Vector Machine (SVM) - Radial rbf

In [26]:
classifier_radial = SVC(kernel='rbf', gamma=0.5, C=10)
classifier_radial.fit(X_train, y_train)

SVC(C=10, gamma=0.5)

In [27]:
y_train_pred = classifier_radial.predict(X_train)
y_test_pred = classifier_radial.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.6046511627906976

In [28]:
classifier_radial.n_support_

array([180, 154], dtype=int32)

## Grid Search

In [29]:
params = {'C':(0.01,0.05, 0.1, 0.5, 1, 5, 10, 50), 
          'gamma':(0.001, 0.01, 0.1, 0.5, 1)} 
clf_svm_r = SVC(kernel='rbf')
svm_grid_rad = GridSearchCV(clf_svm_r, params, n_jobs=-1,
                            cv=3, verbose=1, scoring='accuracy') 
svm_grid_rad.fit(X_train, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             scoring='accuracy', verbose=1)

In [30]:
svm_grid_rad.best_params_ 

{'C': 50, 'gamma': 0.001}

In [31]:
radsvm_clf = svm_grid_rad.best_estimator_
accuracy_score(y_test, radsvm_clf.predict(X_test))

0.7674418604651163

# Support Vector Machine (SVM) - Sigmoid

In [32]:
classifier_sigmoid = SVC(kernel='sigmoid', gamma=0.5, C=0.5)
classifier_sigmoid.fit(X_train, y_train)

SVC(C=0.5, gamma=0.5, kernel='sigmoid')

In [33]:
y_train_pred = classifier_sigmoid.predict(X_train)
y_test_pred = classifier_sigmoid.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.627906976744186

In [34]:
classifier_radial.n_support_

array([87, 85], dtype=int32)